<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'FestingerVault\\AccessRoles' => $baseDir . '/includes/src/AccessRoles.php',
    'FestingerVault\\Admin' => $baseDir . '/includes/src/Admin.php',
    'FestingerVault\\AutoUpdate' => $baseDir . '/includes/src/AutoUpdate.php',
    'FestingerVault\\Constants' => $baseDir . '/includes/src/Constants.php',
    'FestingerVault\\Enqueue' => $baseDir . '/includes/src/Enqueue.php',
    'FestingerVault\\Helper' => $baseDir . '/includes/src/Helper.php',
    'FestingerVault\\Installer' => $baseDir . '/includes/src/Installer.php',
    'FestingerVault\\Plugin' => $baseDir . '/includes/src/Plugin.php',
    'FestingerVault\\RestAPI' => $baseDir . '/includes/src/RestAPI.php',
    'FestingerVault\\Upgrade' => $baseDir . '/includes/src/Upgrade.php',
    'FestingerVault\\ViteAssets' => $baseDir . '/includes/src/ViteAssets.php',
    'FestingerVault\\api\\Announcement' => $baseDir . '/includes/src/api/Announcement.php',
    'FestingerVault\\api\\ApiBase' => $baseDir . '/includes/src/api/ApiBase.php',
    'FestingerVault\\api\\Collection' => $baseDir . '/includes/src/api/Collection.php',
    'FestingerVault\\api\\Disclaimer' => $baseDir . '/includes/src/api/Disclaimer.php',
    'FestingerVault\\api\\History' => $baseDir . '/includes/src/api/History.php',
    'FestingerVault\\api\\Item' => $baseDir . '/includes/src/api/Item.php',
    'FestingerVault\\api\\License' => $baseDir . '/includes/src/api/License.php',
    'FestingerVault\\api\\Popular' => $baseDir . '/includes/src/api/Popular.php',
    'FestingerVault\\api\\Setting' => $baseDir . '/includes/src/api/Setting.php',
    'FestingerVault\\api\\Update' => $baseDir . '/includes/src/api/Update.php',
    'FestingerVault\\exceptions\\ItemDetailErrorException' => $baseDir . '/includes/src/exceptions/ItemDetailErrorException.php',
    'FestingerVault\\exceptions\\ItemDownloadDetailException' => $baseDir . '/includes/src/exceptions/ItemDownloadDetailException.php',
);
